### PR TITLE
Sitegate Updates

### LINKED ISSUE #87: SiteGate: Support `showForm: false`
Currently the option to create a SiteGate without a form is broken. Setting `showForm: false` for a sitegate widget results in a js error. We should fix this, and potentially rework the sitegate widget to support a message with a single confirm button.

### PR DESCRIPTION
**Pull request by sarahyablok**
closes #87 

A small update to sitegate, to make `showForm: false` work and set the id in the cookie for Unlocking. We've also decided to require an id to be set on all widgets, which is the big update here.

### CODE REVIEW

File: dist/pathfora.js [hunk 1]
```diff
@@ -1714,23 +1709,9 @@
...
-      if (!config.id &&
-           config.displayConditions &&
-           typeof config.displayConditions.hideAfterAction !== 'undefined') {
-        delete config.displayConditions.hideAfterAction;
-
-        throw new Error('Widgets with the hideAfterAction displayConditions need a preset id value. Display condition denied.');
-      }
-
-      widget.id = config.id || utils.generateUniqueId();
+      if (!config.id)
```
Comment (markhayden) [inline dist/pathfora.js]: same thing with the `{}` for consistency

File: dist/pathfora.js [hunk 2]
```diff
@@ -2259,8 +2240,12 @@
 
       node = core.createWidgetHtml(widget);
 
-      if (widget.showSocialLogin)
+      if (widget.showSocialLogin) {
+        if (widget.showForm === false)
```
Comment (markhayden) [inline dist/pathfora.js]: and here

File: dist/pathfora.js [hunk 3]
```diff
@@ -931,15 +929,18 @@
...
+                node.removeChild(child);
+                child = node.querySelector('input');
+              }
 
-            node = widget.querySelector('.pf-sitegate-centered-label');
+              child = node.querySelector('.pf-sitegate-clear');
 
-            if (node.parentNode) {
-              node.parentNode.removeChild(node);
+              if (child)
```
Comment (markhayden) [inline dist/pathfora.js]: and here

File: examples/site-gating-widget.html [hunk 4]
```diff
@@ -15,17 +15,14 @@
...
-    <script src="../dist/pathfora.min.js"></script>
+    <script src="../dist/pathfora.js"></script>
     <script>
       var gate = new window.pathfora.SiteGate({
         headline: 'Blocking Widget',
+        id: "gate-widget",
         msg: 'Submit this widget to access the website.',
-        showForm: true,
-        showSocialLogin: true
+        okMessage: "Submit",
```
Comment (markhayden) [inline examples/site-gating-widget.html]: don't need a comma here

File: examples/social-API.html [hunk 5]
```diff
@@ -2,93 +2,20 @@
...
     <script src="https://api.lytics.io/api/tag/0d47e6304d12858905b4f111090a68a1/lio.js"></script>
     <script src="../dist/pathfora.min.js"></script>
     <script>
       var widgets = [];
 
       var form1 = new window.pathfora.Form({
         msg: 'lipsum',
+        id: 'social-widget',
+        showSocialLogin: true,
         headline: 'lipsum',
```
Comment (markhayden) [inline examples/social-API.html]: extra comma
